### ISSUE TITLE
Error adding vanilla actions to non-player objects on respawn

### ISSUE THREAD

**Issue by Dexious** [nicholasclark-artist/DCG#60]
**Arma 3 Version:** `1.64` (stable)     
**CBA Version:** `v3.1.0.160928`   
**DCG Version:** `v3.1.0.6` 

**Server Mods:**
- `@CBA_A3`
- `@dcg`

**Description:**
Player after respawn loses the scroll actions.

Error:

See RPT @ 21:28:35

**Steps to reproduce:**
1) Load the mission.
2) Respawn.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

**RPT log file:**
RPT - http://pastebin.com/esnPdnNb
Mission - https://github.com/Dexious/Tanoa_Lib0924_Dex/raw/master/Tanoa_Lib0924_Dex_r5.Tanoa.pbo

**Comment by nicholasclark-artist** [comment]
when the passed object is anything other than _player_, the addaction's respawn eventhandler fails. fixed in [FUNC(setAction)](https://github.com/nicholasclark-artist/DCG/blob/master/addons/main/functions/fnc_setAction.sqf) and adjusted [FUNC(removeAction)](https://github.com/nicholasclark-artist/DCG/blob/master/addons/main/functions/fnc_removeAction.sqf) to fit new code.
